openapi: 3.0.0
info:
  title: order-management-api
  version: '1.0'
  description: Api to add and read additional info for vipps orders
  contact:
    name: Team ecom
    url: 'https://vipps.no/kontakt-oss/bedrift/vipps/'
servers:
  - url: api.vipps.no/order-management
    description: vipps order management api
paths:
  '/v1/order/{vippsTransactionId}':
    parameters:
      - schema:
          type: string
        name: vippsTransactionId
        in: path
        required: true
    get:
      summary: Get info by vippsTransactionId
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
              examples:
                Retrieve order info:
                  value:
                    category: ticket
                    orderDetailsUrl: 'https://www.vipps.no'
                    imageIds:
                      - laptop_image4433
        '404':
          description: User Not Found
      operationId: fetch_order_info_v1
      description: Retrive the metadata for an order
      parameters:
        - schema:
            type: string
          in: header
          name: Ocp-Apim-Subscription-Key
          description: SubKey
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer token
          required: true
      tags:
        - Vipps order management api
    post:
      summary: Add info to vippsTransactionId
      operationId: post_order_info_v1
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
            examples:
              Adding metadata with one image:
                value:
                  category: general
                  orderDetailsUrl: 'https://www.vipps.no'
                  imageIds:
                    - laptop_image4433
      description: 'Post additional information about an order that will show up on the vipps receipt. '
      parameters:
        - schema:
            type: string
          in: header
          name: Ocp-Apim-Subscription-Key
          description: SubKey
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer token
          required: true
      tags:
        - Vipps order management api
  /v1/image:
    post:
      summary: Add an image to vipps
      operationId: post_image_v1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageId:
                    type: string
              examples:
                example-1:
                  value:
                    imageId: laptop_image4433
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                imageId:
                  type: string
                  description: Id of the image to be added
                src:
                  type: string
                  description: 'Src of the image, like a base64 encoded string'
                type:
                  type: string
                  enum:
                    - base64
              required:
                - imageId
                - src
                - type
            examples:
              example-1:
                value:
                  imageId: laptop_image4433
                  src: iVBORw0KGgoAAAANSUhEUgAAAKsAAADVCAMAAAAfHv
                  type: base64
          application/xml:
            schema:
              type: object
              properties: {}
      description: Endpoint for uploading images to Vipps. A imageId will be returned that can be used when adding metadata to Vipps Transactions
      parameters:
        - schema:
            type: string
          in: header
          name: Ocp-Apim-Subscription-Key
          description: SubKey
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer token
          required: true
      tags:
        - Vipps order management api
components:
  schemas:
    Metadata:
      title: Metadata
      type: object
      x-examples:
        example-1:
          category: general
          orderDetailsUrl: 'https://www.vipps.no'
          imageId:
            - laptop_image4433
      properties:
        category:
          type: string
          enum:
            - general
            - receipt
            - orderConfirmation
            - delivery
            - ticket
            - booking
          description: Enum containing different categories. These will be shown and might behave diferently in the app
        orderDetailsUrl:
          type: string
          example: 'https://www.vipps.no'
          format: uri
          description: URL linking back to the merchant.
        imageIds:
          type: array
          description: list of imageIds linked to this transaction
          items:
            type: string
      required:
        - category
        - orderDetailsUrl
  securitySchemes: {}
tags:
  - name: Vipps order management api
